[build] 
  publish = "dist"
  command = "yarn build"
  functions = ".functions"

[[redirects]]
  from = "/test1"
  to = "/.netlify/functions/slug"
  status = 200
  force = true
  headers = {X-From = "SLUG-TEST-1", X-Netlify-Hostname = "test1.com"}

[[redirects]]
  from = "/test2"
  to = "/.netlify/functions/slug"
  status = 200
  force = true
  headers = {X-From = "SLUG-TEST-2", X-Netlify-Hostname = "test2.com"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    