[build] 
  publish = "dist"
  command = "yarn build"
  functions = ".functions"

[[redirects]]
  from = "/test1"
  to = "/.netlify/functions/slug"
  status = 200
  force = true

[[redirects]]
  from = "/test2"
  to = "/.netlify/functions/slug"
  status = 200
  force = true
