[build] 
  publish = "dist"
  command = "yarn build"
  functions = ".functions"

[[redirects]]
  from = "/a"
  to = "/.netlify/functions/from"
  status = 200
  force = true
  headers = {X-From = "SLUG-A", X-Custom-Token = "my custom token"}

[[redirects]]
  from = "/b"
  to = "/.netlify/functions/from"
  status = 200
  force = true
  headers = {X-From = "SLUG-B", X-Custom-Token = "my custom token"}
