[build] 
  publish = "dist"
  command = "yarn build"
  functions = ".functions"

[[redirects]]
  from = "/a"
  to = "/.netlify/functions/test"
  status = 200
  headers = {X-From = "https://a.example.com"}

[[redirects]]
  from = "/b"
  to = "/.netlify/functions/test"
  status = 200
  headers = {X-From = "https://b.example.com"}
